environment_version: 1
credentials:
- type: aws
  id: hrZ8DknYAgaqPzC6
  description: amazon
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: general
  id: UEQcqHQLHdarepvs
  description: DOC_DB_PASSWORD
  value: DOC_DB_PASSWORD
- type: general
  id: dT1v50FLEG6iOlZy
  description: DOC_DB_SSH_PASSWORD
  value: DOC_DB_SSH_PASSWORD
- type: general
  id: rbEnz6qcQqu7NUFi
  description: DOC_DB_HOST
  value: DOC_DB_HOST
- type: general
  id: B6SSrH1JgYzUCgLB
  description: DOC_DB_USERNAME
  value: DOC_DB_USERNAME
- type: general
  id: IpQgrvuKAKA385zC
  description: DOC_DB_SSH_HOST
  value: DOC_DB_SSH_HOST
- type: general
  id: jQ4tMAHxKYJvd7J2
  description: DOC_DB_SSH_USERNAME
  value: DOC_DB_SSH_USERNAME
